DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS bets;
DROP TABLE IF EXISTS matches;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  score INTEGER
);

CREATE TABLE bets (
  user_id INTEGER,
  match_id INTEGER,
  result1 INTEGER,
  result2 INTEGER
);

CREATE TABLE matches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  country1 TEXT NOT NULL,
  country2 TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  result1 INTEGER,
  result2 INTEGER
);